services:
  - type: web
    name: tcs-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: SECRET_KEY
        generateValue: true
      - key: MOCK_DATA
        value: "true" 