services:
  - type: web
    name: tcs-app
    runtime: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=all --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: SECRET_KEY
        generateValue: true
      - key: MOCK_DATA
        value: "true" 